# Generated by Django 5.2.3 on 2025-06-22 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa (np. imię i nazwisko)')),
                ('status', models.CharField(choices=[('new', 'Nowy'), ('first_contact', 'Pierwszy kontakt'), ('interested', 'Zainteresowany'), ('no_answer', 'Brak odpowiedzi'), ('no_details', 'Brak konkretów'), ('lost', 'Stracony')], default='new', max_length=20, verbose_name='Status')),
                ('zrodlo', models.CharField(choices=[('fb', 'Facebook'), ('tg', 'Telegram'), ('ig', 'Instagram'), ('ad', 'Ogłoszenie'), ('other', 'Inne')], max_length=20, verbose_name='Źródło')),
                ('komentarz', models.TextField(blank=True, verbose_name='Komentarz')),
                ('biuro', models.CharField(blank=True, max_length=100, verbose_name='Biuro')),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('zaktualizowano', models.DateTimeField(auto_now=True)),
                ('menedzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leady', to=settings.AUTH_USER_MODEL, verbose_name='Menedżer')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leady',
                'ordering': ['-utworzono'],
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=255, verbose_name='Imię i nazwisko')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('pesel', models.CharField(blank=True, max_length=11, verbose_name='PESEL')),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('menedzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klienci', to=settings.AUTH_USER_MODEL, verbose_name='Menedżer')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.lead', verbose_name='Powiązany lead')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255, verbose_name='Tytuł/Opis zadania')),
                ('termin', models.DateTimeField(verbose_name='Termin wykonania')),
                ('wykonane', models.BooleanField(default=False, verbose_name='Czy wykonane?')),
                ('object_id', models.PositiveIntegerField()),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('przypisane_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zadania', to=settings.AUTH_USER_MODEL, verbose_name='Przypisane do')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ['termin'],
            },
        ),
    ]
